# Generated by Django 6.0.6 on 2026-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='created_at',
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, default='students/passports/default.png', null=True, upload_to='students/passports/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('school_admin', 'School System Administrator'), ('headteacher', 'Headteacher'), ('bursar', 'School Bursar'), ('nurse', 'School Nurse'), ('librarian', 'School Librarian'), ('lab_technician', 'Lab Technician'), ('dos', 'Director of Studies'), ('class_teacher', 'Class Teacher'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], default='teacher', max_length=20),
        ),
    ]
