# Generated by Django 6.0.6 on 2026-06-24 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('school_admin', 'School System Administrator'), ('headteacher', 'Headteacher'), ('dos', 'Director of Studies'), ('bursar', 'School Bursar'), ('nurse', 'School Nurse'), ('librarian', 'School Librarian'), ('lab_technician', 'Lab Technician'), ('class_teacher', 'Class Teacher'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], default='teacher', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School assignment. Leave blank ONLY for System Admin.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('aggregate_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('headteacher_remark', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classlevel')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_report_cards', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.studentprofile')),
            ],
            options={
                'ordering': ['term', 'student'],
                'unique_together': {('school', 'student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ReportCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_term', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('end_term', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.reportcard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'ordering': ['subject__name'],
                'unique_together': {('report_card', 'subject')},
            },
        ),
    ]
