# Generated by Django 6.0.6 on 2026-09-08 19:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_election_position_candidate_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('school_address', models.TextField(blank=True)),
                ('school_phone', models.CharField(blank=True, max_length=100)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('school_website', models.URLField(blank=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('school_motto', models.CharField(blank=True, max_length=200)),
                ('report_card_title', models.CharField(default='ACADEMIC REPORT CARD', max_length=100)),
                ('header_text', models.TextField(blank=True, help_text='Custom header text to appear on report cards')),
                ('footer_text', models.TextField(blank=True, help_text='Custom footer text to appear on report cards')),
                ('show_grade_scale', models.BooleanField(default=True)),
                ('show_teacher_signature', models.BooleanField(default=True)),
                ('show_head_teacher_signature', models.BooleanField(default=True)),
                ('grade_a_min', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_b_min', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_c_min', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_d_min', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_e_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_a_label', models.CharField(default='Exceptional', max_length=50)),
                ('grade_b_label', models.CharField(default='Outstanding', max_length=50)),
                ('grade_c_label', models.CharField(default='Satisfactory', max_length=50)),
                ('grade_d_label', models.CharField(default='Basic', max_length=50)),
                ('grade_e_label', models.CharField(default='Elementary', max_length=50)),
                ('subject_columns', models.JSONField(blank=True, default=list, help_text='Custom subject columns')),
                ('primary_color', models.CharField(default='#1a237e', max_length=7)),
                ('secondary_color', models.CharField(default='#0d47a1', max_length=7)),
                ('accent_color', models.CharField(default='#e8eaf6', max_length=7)),
                ('term_dates', models.JSONField(blank=True, default=dict, help_text='Term start and end dates')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Additional custom fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.school')),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
