# Generated by Django 6.0.6 on 2026-09-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='subject_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='term_dates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
